In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
df= pd.read_csv('admission.csv')

In [6]:
df.head()

   ADMIT  GRE   GPA  RANK
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [7]:
df.shape

(400, 4)

In [8]:
df.size

1600

In [9]:
df.ndim

2

In [10]:
df.columns

Index(['ADMIT', 'GRE', 'GPA', 'RANK'], dtype='object')

In [11]:
df.isnull().sum()

ADMIT    0
GRE      0
GPA      0
RANK     0
dtype: int64

In [13]:
df[df.duplicated()]

     ADMIT  GRE   GPA  RANK
59       0  600  2.82     4
77       1  800  4.00     3
202      1  700  4.00     1
263      1  620  3.95     3
398      0  700  3.65     2

In [14]:
target=df[['ADMIT']]
features= df.drop(columns='ADMIT')

In [20]:
x_train,x_test,y_train,y_test= train_test_split(features,target,test_size=0.25,random_state=100)

In [21]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(300, 3)
(300, 1)
(100, 3)
(100, 1)

In [23]:
log_model= LogisticRegression()

In [24]:
log_model.fit(x_train,y_train)

C:\Users\excel\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [35]:
y_pred= log_model.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [26]:
accuracy_score(y_test,y_pred)

0.63

In [29]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0], dtype=int64)

In [27]:
log_model.predict_proba(x_test)

array([[0.68252193, 0.31747807],
       [0.87744779, 0.12255221],
       [0.48256058, 0.51743942],
       [0.86679746, 0.13320254],
       [0.93027558, 0.06972442],
       [0.69139854, 0.30860146],
       [0.61164889, 0.38835111],
       [0.82789895, 0.17210105],
       [0.78305594, 0.21694406],
       [0.73953192, 0.26046808],
       [0.88266987, 0.11733013],
       [0.58036674, 0.41963326],
       [0.84853288, 0.15146712],
       [0.73136097, 0.26863903],
       [0.62976917, 0.37023083],
       [0.86314428, 0.13685572],
       [0.58562528, 0.41437472],
       [0.88252094, 0.11747906],
       [0.82980417, 0.17019583],
       [0.83263704, 0.16736296],
       [0.87632849, 0.12367151],
       [0.70645687, 0.29354313],
       [0.60348332, 0.39651668],
       [0.52062454, 0.47937546],
       [0.53629978, 0.46370022],
       [0.77364866, 0.22635134],
       [0.74850836, 0.25149164],
       [0.71602515, 0.28397485],
       [0.81709857, 0.18290143],
       [0.84547159, 0.15452841],
       [0.66164926, 0.33835074],
       [0.78144215, 0.21855785],
       [0.42331581, 0.57668419],
       [0.69551824, 0.30448176],
       [0.53071433, 0.46928567],
       [0.81120767, 0.18879233],
       [0.81876361, 0.18123639],
       [0.67499582, 0.32500418],
       [0.92079592, 0.07920408],
       [0.29540838, 0.70459162],
       [0.87969734, 0.12030266],
       [0.74185105, 0.25814895],
       [0.59012382, 0.40987618],
       [0.39797504, 0.60202496],
       [0.68815946, 0.31184054],
       [0.5382032 , 0.4617968 ],
       [0.82991888, 0.17008112],
       [0.74627952, 0.25372048],
       [0.67667315, 0.32332685],
       [0.36536052, 0.63463948],
       [0.52530039, 0.47469961],
       [0.78547954, 0.21452046],
       [0.57301917, 0.42698083],
       [0.69184102, 0.30815898],
       [0.67714742, 0.32285258],
       [0.7733497 , 0.2266503 ],
       [0.59319501, 0.40680499],
       [0.56000346, 0.43999654],
       [0.79160985, 0.20839015],
       [0.57028141, 0.42971859],
       [0.63746728, 0.36253272],
       [0.57852087, 0.42147913],
       [0.66959437, 0.33040563],
       [0.88466214, 0.11533786],
       [0.58562528, 0.41437472],
       [0.78872708, 0.21127292],
       [0.64431374, 0.35568626],
       [0.61771194, 0.38228806],
       [0.76757833, 0.23242167],
       [0.81086284, 0.18913716],
       [0.74372806, 0.25627194],
       [0.8802683 , 0.1197317 ],
       [0.69530903, 0.30469097],
       [0.4061002 , 0.5938998 ],
       [0.59471442, 0.40528558],
       [0.75450123, 0.24549877],
       [0.92068418, 0.07931582],
       [0.73808829, 0.26191171],
       [0.73663955, 0.26336045],
       [0.29075863, 0.70924137],
       [0.69490645, 0.30509355],
       [0.65283889, 0.34716111],
       [0.67533167, 0.32466833],
       [0.37843411, 0.62156589],
       [0.82513355, 0.17486645],
       [0.6456761 , 0.3543239 ],
       [0.8552635 , 0.1447365 ],
       [0.60954777, 0.39045223],
       [0.93026421, 0.06973579],
       [0.85989798, 0.14010202],
       [0.49240363, 0.50759637],
       [0.78558692, 0.21441308],
       [0.64742567, 0.35257433],
       [0.42933499, 0.57066501],
       [0.81887023, 0.18112977],
       [0.52363727, 0.47636273],
       [0.55261754, 0.44738246],
       [0.85591987, 0.14408013],
       [0.48999201, 0.51000799],
       [0.61276178, 0.38723822]])

In [31]:
y_pred_new=[1 if x[1]>=0.4 else 0 for x in log_model.predict_proba(x_test)]

In [33]:
y_pred_new=[0 if x[0]>=0.6 else 1 for x in log_model.predict_proba(x_test)]

In [34]:
accuracy_score(y_test,y_pred_new)

0.64